#!/usr/bin/env python3
"""
THIS SCRIPT IS ENTIRELY GENERATED BY AI.

Safely rename C enum types and constants in a codebase based on a JSON configuration mapping table.
Scans source directories directly, allowing it to work without a complete compile_commands.json.
Uses clang.cindex (libclang) for precise AST-based location finding.
"""
import clang.cindex
import json
import os
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "../../"))

# ---------- Configuration ----------
SRC_DIRS = ["src", "include"]       # Directories to scan for source and header files
# Directories to exclude from scanning
EXCLUDE_DIRS = [
    os.path.join(PROJECT_ROOT, "include/vividx"),
]
CONFIG_FILE = "rename_config.json"  # Mapping configuration file
# Basic compiler flags/include paths for libclang parsing
DEFAULT_ARGS = ["-std=c++20", "-Iinclude", "-x", "c++"]
# -----------------------------------

def file_contains_targets(filepath, target_names):
    """Quickly check if the file contains any of the target names using raw text search."""
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
            return any(name in content for name in target_names)
    except Exception:
        return False

def get_line_number(content, offset):
    """Calculate the line number from a character offset."""
    return content.count('\n', 0, offset) + 1

def load_config(config_path):
    if not os.path.exists(config_path):
        print(f"[Error] Configuration file ({config_path}) does not exist.")
        exit(1)
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)

def get_source_files(directories):
    """Recursively find all C source and header files in the specified directories."""
    extensions = (".h", ".cpp", ".hpp")
    source_files = []
    for directory in directories:
        abs_dir = os.path.join(PROJECT_ROOT, directory)

        if not os.path.exists(abs_dir):
            print(f"[Warning] Directory '{abs_dir}' does not exist. Skipping.")
            continue
        for root, _, files in os.walk(abs_dir):
            # Skip if current path matches any exclude directory
            if any(root.startswith(exc) for exc in EXCLUDE_DIRS):
                continue
            for file in files:
                if file.endswith(extensions):
                    source_files.append(os.path.abspath(os.path.join(root, file)))
    return source_files

def collect_usages(tu, type_map, const_map, usages_by_file, target_filepath):
    """
    Collect enum usages strictly for the target file, 
    skipping massive header file token iteration overhead.
    """
    target_map = {**type_map, **const_map}
    abs_target_path = os.path.abspath(target_filepath)

    # 1. Token-based scan (optimized to quickly skip tokens outside the target file)
    for token in tu.get_tokens(extent=tu.cursor.extent):
        loc = token.location
        if loc.file is not None:
            # Only process tokens belonging to the target file itself
            if os.path.abspath(loc.file.name) == abs_target_path:
                if token.kind == clang.cindex.TokenKind.IDENTIFIER:
                    name = token.spelling
                    if name in target_map:
                        start = token.extent.start.offset
                        end = token.extent.end.offset
                        usages_by_file[abs_target_path].add((start, end, name, target_map[name]))

    # 2. AST declaration check (restricted to target file)
    def visit(node):
        loc = node.location
        if loc.file is not None:
            if os.path.abspath(loc.file.name) == abs_target_path:
                if node.kind in (clang.cindex.CursorKind.ENUM_CONSTANT_DECL, clang.cindex.CursorKind.ENUM_DECL):
                    name = node.spelling
                    if name in target_map:
                        start = node.extent.start.offset
                        usages_by_file[abs_target_path].add((start, start + len(name), name, target_map[name]))

        for child in node.get_children():
            visit(child)

    visit(tu.cursor)

def apply_renames_to_file(filepath, spans):
    """Perform replacements from back to front to prevent offset shifting."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Sort in descending order based on the end offset (start, end, old_name, new_name)
    spans_sorted = sorted(spans, key=lambda s: s[1], reverse=True)

    for start, end, old_name, new_name in spans_sorted:
        actual = content[start:end]
        if actual != old_name:
            print(f"  [Warning] {filepath}:{start} Expected '{old_name}' != Actual '{actual}' -> Skipping")
            continue
        content = content[:start] + new_name + content[end:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

def main():
    config = load_config(CONFIG_FILE)
    type_map = config.get("enum_types", {})
    const_map = config.get("enum_constants", {})

    print(f"Config loaded: {len(type_map)} types, {len(const_map)} constants mapped.")

    # Combine all target names for quick searching
    target_names = set(type_map.keys()).union(set(const_map.keys()))

    source_files = get_source_files(SRC_DIRS)
    print(f"Found {len(source_files)} files to process.")

    index = clang.cindex.Index.create()
    tus = []

    for filepath in source_files:
        # Skip parsing if the file text doesn't contain any target names
        if not file_contains_targets(filepath, target_names):
            continue

        print(f"[Parsing] {filepath}")
        try:
            # Parse each file directly using basic arguments
            tu = index.parse(filepath, args=DEFAULT_ARGS)
            tus.append(tu)
        except Exception as e:
            print(f"  [Error] Failed to parse {filepath}: {e}")
    print("Parsing done.")

    # Collect usages per file with progress tracking
    usages_by_file = defaultdict(set)
    total_tus = len(tus)

    print(f"\nCollecting usages from {total_tus} parsed files...")
    for idx, tu in enumerate(tus, 1):
        # tu.spelling gives the filename of the translation unit
        filepath = os.path.abspath(tu.spelling)
        print(f"[{idx}/{total_tus}] Analyzing: {os.path.basename(filepath)}")

        # Pass the filepath to restrict iteration overhead
        collect_usages(tu, type_map, const_map, usages_by_file, filepath)

    if not usages_by_file:
        print("\nNo matching enum types or constants found to rename.")
        return

    print(f"\nFound changes across {len(usages_by_file)} files.")

    # Process file by file with confirmation preview
    for filepath, spans in usages_by_file.items():
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        print(f"\n========================================")
        print(f"File: {filepath} ({len(spans)} changes)")
        print(f"========================================")

        # Show changes in ascending order of offset for readability
        for start, end, old_name, new_name in sorted(spans, key=lambda s: s[0]):
            line_no = get_line_number(content, start)
            print(f"  Line {line_no:4d}: {old_name}  ->  {new_name}")

        choice = input("\nApply changes to this file? [y]es / [n]o / [q]uit: ").strip().lower()

        if choice == 'q':
            print("Aborted by user.")
            break
        elif choice == 'n':
            print("Skipped this file.")
            continue
        elif choice == 'y' or choice == '':
            print(f"[Replacing] {filepath}")
            apply_renames_to_file(filepath, spans)
        else:
            print("Invalid input. Skipped this file.")

    print("\nDone. Be sure to check the results with git diff.")

if __name__ == "__main__":
    main()
