#!/bin/sh

mkdir -p build
cd build ; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja .. ; ninja
cd ..

case "$1" in
    debug)
        OUT_DIR="out/Debug"
        ARGS_FILE="gn-args.trace.txt"
        ;;
    *)
        OUT_DIR="out/Shared"
        ARGS_FILE="gn-args.txt"
        ;;
esac

bin/gn gen "$OUT_DIR" --args="$(cat "$ARGS_FILE")"
ninja -C "$OUT_DIR"
