/*
 * Copyright 2013 Google Inc.
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 *
 * 2026, Aspen Schneider.
 */
#ifndef VIVIDX_CORE_IMAGE_INFO_H
#define VIVIDX_CORE_IMAGE_INFO_H

#include <stddef.h>

#include <vividx/common.h>
#include <vividx/core/alpha-type.h>
#include <vividx/core/color-type.h>
#include <vividx/core/size.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef struct vx_color_space_t vx_color_space_t;

/// \struct vx_color_info_t
///
/// Describes pixel and encoding. SkImageInfo can be created from SkColorInfo by
/// providing dimensions.
///
/// It encodes how pixel bits describe alpha, transparency; color components red, blue,
/// and green; and SkColorSpace, the range and linearity of colors.
typedef struct vx_color_info_t vx_color_info_t;

/// \struct vx_image_info_t
///
/// Describes pixel and encoding. `vx_image_info_t` can be created from
/// `vx_color_info_t` by providing dimensions.
///
/// It encodes how pixel bits describe alpha, transparency; color components
/// red, blue, and green; and SkColorSpace, the range and linearity of colors.
typedef struct vx_image_info_t vx_image_info_t;

/** \enum vx_yuv_color_space
    Describes color range of YUV pixels. The color mapping from YUV to RGB varies
    depending on the source. YUV pixels may be generated by JPEG images, standard
    video streams, or high definition video streams. Each has its own mapping from
    YUV to RGB.

    JPEG YUV values encode the full range of 0 to 255 for all three components.
    Video YUV values often range from 16 to 235 for Y and from 16 to 240 for U and V (limited).
    Details of encoding and conversion to RGB are described in YCbCr color space.

    The identity colorspace exists to provide a utility mapping from Y to R, U to G and V to B.
    It can be used to visualize the YUV planes or to explicitly post process the YUV channels.
*/
enum vx_yuv_color_space {
    VX_YUV_COLOR_SPACE_JPEG_FULL,                 //!< describes full range
    VX_YUV_COLOR_SPACE_REC601_LIMITED,            //!< describes SDTV range
    VX_YUV_COLOR_SPACE_REC709_FULL,               //!< describes HDTV range
    VX_YUV_COLOR_SPACE_REC709_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_8BIT_FULL,          //!< describes UHDTV range, non-constant-luminance
    VX_YUV_COLOR_SPACE_BT2020_8BIT_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_10BIT_FULL,
    VX_YUV_COLOR_SPACE_BT2020_10BIT_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_12BIT_FULL,
    VX_YUV_COLOR_SPACE_BT2020_12BIT_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_16BIT_FULL,
    VX_YUV_COLOR_SPACE_BT2020_16BIT_LIMITED,
    VX_YUV_COLOR_SPACE_FCC_FULL,                  //!< describes FCC range
    VX_YUV_COLOR_SPACE_FCC_LIMITED,
    VX_YUV_COLOR_SPACE_SMPTE240_FULL,             //!< describes SMPTE240M range
    VX_YUV_COLOR_SPACE_SMPTE240_LIMITED,
    VX_YUV_COLOR_SPACE_YDZDX_FULL,                //!< describes YDZDX range
    VX_YUV_COLOR_SPACE_YDZDX_LIMITED,
    VX_YUV_COLOR_SPACE_GBR_FULL,                  //!< describes GBR range
    VX_YUV_COLOR_SPACE_GBR_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_8BIT_FULL,           //!< describes YCgCo matrix
    VX_YUV_COLOR_SPACE_YCGCO_8BIT_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_10BIT_FULL,
    VX_YUV_COLOR_SPACE_YCGCO_10BIT_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_12BIT_FULL,
    VX_YUV_COLOR_SPACE_YCGCO_12BIT_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_16BIT_FULL,
    VX_YUV_COLOR_SPACE_YCGCO_16BIT_LIMITED,
    VX_YUV_COLOR_SPACE_IDENTITY,                  //!< maps Y->R, U->G, V->B

    VX_YUV_COLOR_SPACE_LASTENUM = VX_YUV_COLOR_SPACE_IDENTITY, //!< last valid value

    // Legacy (deprecated) names:
    VX_YUV_COLOR_SPACE_JPEG = VX_YUV_COLOR_SPACE_JPEG_FULL,
    VX_YUV_COLOR_SPACE_REC601 = VX_YUV_COLOR_SPACE_REC601_LIMITED,
    VX_YUV_COLOR_SPACE_REC709 = VX_YUV_COLOR_SPACE_REC709_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020 = VX_YUV_COLOR_SPACE_BT2020_8BIT_LIMITED,
};


//!<==================
//!< Color Info
//!<==================

VX_PUBLIC vx_color_info_t* vx_color_info_new(enum vx_color_type ct,
                                             enum vx_alpha_type at,
                                             vx_color_space_t *cs);

VX_PUBLIC vx_color_space_t* vx_color_info_color_space(
    const vx_color_info_t *color_info);

VX_PUBLIC enum vx_color_type vx_color_info_color_type(
    const vx_color_info_t *color_info);

VX_PUBLIC enum vx_alpha_type vx_color_info_alpha_type(
    const vx_color_info_t *color_info);

VX_PUBLIC void vx_color_info_free(vx_color_info_t *color_info);

//!<==================
//!< Image Info
//!<==================

struct vx_image_info_t {
    vx_color_info_t *color_info;
    vx_size_i_t dimensions;
};

// static vx_image_info_t vx_image_info_make()
// {
//     vx_image_info_t info;
//     info.color_info = vx_color_info_make();
//     info.dimensions = vx_size_i_make(0, 0);
//     return info;
// }

#ifdef __cplusplus
}
#endif // __cplusplus

#endif /* VIVIDX_CORE_IMAGE_INFO_H */
