/*
 * Copyright 2013 Google Inc.
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 *
 * 2026, Aspen Schneider.
 */
#ifndef VIVIDX_CORE_IMAGE_INFO_H
#define VIVIDX_CORE_IMAGE_INFO_H

#include <stdbool.h>
#include <stddef.h>

#include <vividx/common.h>
#include <vividx/core/alpha-type.h>
#include <vividx/core/color-type.h>
#include <vividx/core/math.h>
#include <vividx/core/size.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

typedef struct vx_color_space_t vx_color_space_t;

/// \struct vx_color_info_t
///
/// Describes pixel and encoding. SkImageInfo can be created from SkColorInfo by
/// providing dimensions.
///
/// It encodes how pixel bits describe alpha, transparency; color components red, blue,
/// and green; and SkColorSpace, the range and linearity of colors.
typedef struct vx_color_info_t vx_color_info_t;

/// \struct vx_image_info_t
///
/// Describes pixel and encoding. `vx_image_info_t` can be created from
/// `vx_color_info_t` by providing dimensions.
///
/// It encodes how pixel bits describe alpha, transparency; color components
/// red, blue, and green; and SkColorSpace, the range and linearity of colors.
typedef struct vx_image_info_t vx_image_info_t;

/** \enum vx_yuv_color_space
    Describes color range of YUV pixels. The color mapping from YUV to RGB varies
    depending on the source. YUV pixels may be generated by JPEG images, standard
    video streams, or high definition video streams. Each has its own mapping from
    YUV to RGB.

    JPEG YUV values encode the full range of 0 to 255 for all three components.
    Video YUV values often range from 16 to 235 for Y and from 16 to 240 for U and V (limited).
    Details of encoding and conversion to RGB are described in YCbCr color space.

    The identity colorspace exists to provide a utility mapping from Y to R, U to G and V to B.
    It can be used to visualize the YUV planes or to explicitly post process the YUV channels.
*/
enum vx_yuv_color_space {
    VX_YUV_COLOR_SPACE_JPEG_FULL,                 //!< describes full range
    VX_YUV_COLOR_SPACE_REC601_LIMITED,            //!< describes SDTV range
    VX_YUV_COLOR_SPACE_REC709_FULL,               //!< describes HDTV range
    VX_YUV_COLOR_SPACE_REC709_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_8BIT_FULL,          //!< describes UHDTV range, non-constant-luminance
    VX_YUV_COLOR_SPACE_BT2020_8BIT_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_10BIT_FULL,
    VX_YUV_COLOR_SPACE_BT2020_10BIT_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_12BIT_FULL,
    VX_YUV_COLOR_SPACE_BT2020_12BIT_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020_16BIT_FULL,
    VX_YUV_COLOR_SPACE_BT2020_16BIT_LIMITED,
    VX_YUV_COLOR_SPACE_FCC_FULL,                  //!< describes FCC range
    VX_YUV_COLOR_SPACE_FCC_LIMITED,
    VX_YUV_COLOR_SPACE_SMPTE240_FULL,             //!< describes SMPTE240M range
    VX_YUV_COLOR_SPACE_SMPTE240_LIMITED,
    VX_YUV_COLOR_SPACE_YDZDX_FULL,                //!< describes YDZDX range
    VX_YUV_COLOR_SPACE_YDZDX_LIMITED,
    VX_YUV_COLOR_SPACE_GBR_FULL,                  //!< describes GBR range
    VX_YUV_COLOR_SPACE_GBR_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_8BIT_FULL,           //!< describes YCgCo matrix
    VX_YUV_COLOR_SPACE_YCGCO_8BIT_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_10BIT_FULL,
    VX_YUV_COLOR_SPACE_YCGCO_10BIT_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_12BIT_FULL,
    VX_YUV_COLOR_SPACE_YCGCO_12BIT_LIMITED,
    VX_YUV_COLOR_SPACE_YCGCO_16BIT_FULL,
    VX_YUV_COLOR_SPACE_YCGCO_16BIT_LIMITED,
    VX_YUV_COLOR_SPACE_IDENTITY,                  //!< maps Y->R, U->G, V->B

    VX_YUV_COLOR_SPACE_LASTENUM = VX_YUV_COLOR_SPACE_IDENTITY, //!< last valid value

    // Legacy (deprecated) names:
    VX_YUV_COLOR_SPACE_JPEG = VX_YUV_COLOR_SPACE_JPEG_FULL,
    VX_YUV_COLOR_SPACE_REC601 = VX_YUV_COLOR_SPACE_REC601_LIMITED,
    VX_YUV_COLOR_SPACE_REC709 = VX_YUV_COLOR_SPACE_REC709_LIMITED,
    VX_YUV_COLOR_SPACE_BT2020 = VX_YUV_COLOR_SPACE_BT2020_8BIT_LIMITED,
};

VX_PUBLIC bool vx_yuv_color_space_is_limited_range(enum vx_yuv_color_space cs);


//!<==================
//!< Color Info
//!<==================

struct vx_color_info_t {
    const vx_color_space_t *color_space;
    enum vx_color_type color_type; // = kUnknown_SkColorType;
    enum vx_alpha_type alpha_type; // = VX_ALPHA_TYPE_UNKNOWN;
};

/// Creates `vx_color_info_t` from `enum vx_color_type` ct, `enum vx_alpha_type`
/// at, and optionally `const vx_color_space_t*` cs.
///
/// If const `vx_color_space_t*` cs is nullptr and `vx_color_info_t` is part of
/// drawing source: `vx_color_space_t*` defaults
/// to sRGB, mapping into SkSurface `vx_color_space_t*`.
///
/// Parameters are not validated to see if their values are legal, or that the
/// combination is supported.
///
/// \return created `vx_color_info_t`.
static inline vx_color_info_t vx_color_info_make(enum vx_color_type ct,
                                                 enum vx_alpha_type at,
                                                 const vx_color_space_t *cs)
{
    vx_color_info_t info;
    info.color_space = cs;
    info.color_type = ct;
    info.alpha_type = at;
    return info;
}

VX_PUBLIC vx_color_info_t vx_color_info_copy_with_alpha_type(
    const vx_color_info_t *color_info, enum vx_alpha_type at);

VX_PUBLIC vx_color_info_t vx_color_info_copy_with_color_type(
    const vx_color_info_t *color_info, enum vx_color_type ct);

VX_PUBLIC vx_color_info_t vx_color_info_copy_with_color_space(
    const vx_color_info_t *color_info, const vx_color_space_t *cs);

VX_PUBLIC const vx_color_space_t* vx_color_info_color_space(
    const vx_color_info_t *color_info);

VX_PUBLIC enum vx_color_type vx_color_info_color_type(
    const vx_color_info_t *color_info);

VX_PUBLIC enum vx_alpha_type vx_color_info_alpha_type(
    const vx_color_info_t *color_info);

VX_PUBLIC bool vx_color_info_is_opaque(const vx_color_info_t *color_info);

VX_PUBLIC bool vx_color_info_gamma_close_to_srgb(const vx_color_info_t *info);

/** Does other represent the same color type, alpha type, and color space? */
VX_PUBLIC bool vx_color_info_eq(const vx_color_info_t *info,
                                const vx_color_info_t *other);

/** Does other represent a different color type, alpha type, or color space? */
VX_PUBLIC bool vx_color_info_ne(const vx_color_info_t *info,
                                const vx_color_info_t *other);

/** Returns number of bytes per pixel required by SkColorType.
    Returns zero if colorType() is kUnknown_SkColorType.

    @return  bytes in pixel

    example: https://fiddle.skia.org/c/@ImageInfo_bytesPerPixel
*/
VX_PUBLIC int vx_color_info_bytes_per_pixel(const vx_color_info_t *ct);

/** Returns bit shift converting row bytes to row pixels.
    Returns zero for kUnknown_SkColorType.

    @return  one of: 0, 1, 2, 3, 4; left shift to convert pixels to bytes

    example: https://fiddle.skia.org/c/@ImageInfo_shiftPerPixel
*/
VX_PUBLIC int vx_color_info_shift_per_pixel(const vx_color_info_t *ct);

//!<==================
//!< Image Info
//!<==================

struct vx_image_info_t {
    vx_color_info_t color_info;
    vx_size_i_t dimensions;
};

static vx_image_info_t vx_image_info_make(vx_size_i_t dimensions,
                                          const vx_color_info_t *color_info)
{
    vx_image_info_t info;
    info.color_info = *color_info;
    info.dimensions = dimensions;
    return info;
}

VX_PUBLIC
enum vx_alpha_type vx_image_info_alpha_type(const vx_image_info_t *info);

VX_PUBLIC
enum vx_color_type vx_image_info_color_type(const vx_image_info_t *info);

VX_PUBLIC
vx_color_space_t* vx_image_info_color_space(const vx_image_info_t *info);

static inline bool vx_image_info_is_empty(const vx_image_info_t *info)
{
    return vx_size_i_is_empty(info->dimensions);
}

static inline bool vx_image_info_is_opaque(const vx_image_info_t *info)
{
    return vx_color_info_is_opaque(&info->color_info);
}

static inline bool vx_image_info_gamma_close_to_srgb(const vx_image_info_t *i)
{
    return vx_color_info_gamma_close_to_srgb(&i->color_info);
}

static inline int vx_image_info_bytes_per_pixel(const vx_image_info_t *info)
{
    return vx_color_info_bytes_per_pixel(&info->color_info);
}

static inline int vx_image_info_shift_per_pixel(const vx_image_info_t *info)
{
    return vx_color_info_shift_per_pixel(&info->color_info);
}

/** Returns minimum bytes per row, computed from pixel width() and SkColorType, which
    specifies bytesPerPixel(). SkBitmap maximum value for row bytes must fit
    in 31 bits.

    @return  width() times bytesPerPixel() as unsigned 64-bit integer
*/
VX_PUBLIC uint64_t vx_image_info_min_row_bytes64(const vx_image_info_t *info);

/** Returns minimum bytes per row, computed from pixel width() and SkColorType, which
    specifies bytesPerPixel(). SkBitmap maximum value for row bytes must fit
    in 31 bits.

    @return  width() times bytesPerPixel() as size_t
*/
VX_PUBLIC size_t vx_image_info_min_row_bytes(const vx_image_info_t *info);

/** Returns byte offset of pixel from pixel base address.

    Asserts in debug build if x or y is outside of bounds. Does not assert if
    rowBytes is smaller than minRowBytes(), even though result may be incorrect.

    @param x         column index, zero or greater, and less than width()
    @param y         row index, zero or greater, and less than height()
    @param rowBytes  size of pixel row or larger
    @return          offset within pixel array

    example: https://fiddle.skia.org/c/@ImageInfo_computeOffset
*/
VX_PUBLIC size_t vx_image_info_compute_offset(const vx_image_info_t *info,
                                              int x,
                                              int y,
                                              size_t rowBytes);

/** Compares SkImageInfo with other, and returns true if width, height, SkColorType,
    SkAlphaType, and SkColorSpace are equivalent.

    @param other  SkImageInfo to compare
    @return       true if SkImageInfo equals other
*/
static inline bool vx_image_info_eq(const vx_image_info_t *info,
                                    const vx_image_info_t *other)
{
    return vx_size_i_eq(info->dimensions, other->dimensions) &&
        vx_color_info_eq(&info->color_info, &other->color_info);
}

/** Compares SkImageInfo with other, and returns true if width, height, SkColorType,
    SkAlphaType, and SkColorSpace are not equivalent.

    @param other  SkImageInfo to compare
    @return       true if SkImageInfo is not equal to other
*/
static inline bool vx_image_info_ne(const vx_image_info_t *info,
                                    const vx_image_info_t *other)
{
    return !(vx_image_info_eq(info, other));
}

/** Returns storage required by pixel array, given SkImageInfo dimensions, SkColorType,
    and rowBytes. rowBytes is assumed to be at least as large as minRowBytes().

    Returns zero if height is zero.
    Returns SIZE_MAX if answer exceeds the range of size_t.

    @param rowBytes  size of pixel row or larger
    @return          memory required by pixel buffer
*/
VX_PUBLIC size_t vx_image_info_compute_byte_size(const vx_image_info_t *info,
                                                 size_t row_bytes);

/** Returns storage required by pixel array, given SkImageInfo dimensions, and
    SkColorType. Uses minRowBytes() to compute bytes for pixel row.

    Returns zero if height is zero.
    Returns SIZE_MAX if answer exceeds the range of size_t.

    @return  least memory required by pixel buffer
*/
static inline size_t vx_image_info_compute_min_byte_size(
    const vx_image_info_t *info)
{
    return vx_image_info_compute_byte_size(info,
        vx_image_info_min_row_bytes(info));
}

/** Returns true if byteSize equals SIZE_MAX. computeByteSize() and
    computeMinByteSize() return SIZE_MAX if size_t can not hold buffer size.

    @param byteSize  result of computeByteSize() or computeMinByteSize()
    @return          true if computeByteSize() or computeMinByteSize() result exceeds size_t
*/
static inline
bool vx_image_info_byte_size_overflowed(const vx_image_info_t *info,
                                        size_t byte_size)
{
    (void)info;
    return SIZE_MAX == byte_size;
}

/** Returns true if rowBytes is valid for this SkImageInfo.

    @param rowBytes  size of pixel row including padding
    @return          true if rowBytes is large enough to contain pixel row and is properly
                        aligned
*/
static inline bool vx_image_info_valid_row_bytes(const vx_image_info_t *info,
                                                 size_t row_bytes)
{
    if (row_bytes < vx_image_info_min_row_bytes64(info)) {
        return false;
    }
    int shift = vx_image_info_shift_per_pixel(info);
    size_t aligned_row_bytes = row_bytes >> shift << shift;
    return aligned_row_bytes == row_bytes;
}

#ifdef __cplusplus
}
#endif // __cplusplus

#endif /* VIVIDX_CORE_IMAGE_INFO_H */
